### ISSUE TITLE
Expanding with word-movement-previous-word-extending isn't moving the cursor at the right place

### ISSUE THREAD

**Issue by CBenoit** [alexherbo2/word-select.kak#1]
Hi,
I suppose this is already a known issue but I wanted to open this issue just to be sure.
Let's say I'm selecting some words using word-movement. `|` is the cursor. Characters between `*` are selected.
Initially:
```
this |is a sentence.
```
I want to select `is a` but I press `W` three times instead of two by mistake:
```
this *is a sentence*|.
```
I want to remove the last word from my selection using `B`, but:
```
*this is a sentence*|.
```
is what I get. The cursor stays at the end and selection is extended to the left from the beginning.

Thus, I need to remove " sentence" from my selection by using `H`, and then (assuming I made the aforementioned mistake) put my cursor at the beginning using `<a-;>` to remove the word using `L`.

**Comment by alexherbo2** [comment]
I stopped working on plugins.

If you have a PR, I’ll happily merge.
